In [2]:
my_list = [1,2,3]


In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)
print (arr)

[1 2 3]


In [7]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [9]:
np.random.rand(2,2)

array([[0.67554706, 0.36707393],
       [0.62617497, 0.56268069]])

In [11]:
np.random.randint(2,20,5)

array([4, 8, 5, 9, 4])

In [16]:
np.random.randn(2,3,3)

array([[[ 0.53175159,  0.71488844, -1.23465358],
        [ 1.33555223,  0.78108633,  0.03825079],
        [-0.18841305, -0.02089709,  0.9698546 ]],

       [[-1.022244  , -1.62251982,  0.84376909],
        [ 1.90965557, -1.67999049, -0.64132845],
        [ 0.56276623,  1.50713001, -0.60914641]]])