In [6]:
my_list = [1,2,3]


In [3]:
import numpy as np

In [7]:
arr = np.array(my_list)
print (arr)

[1 2 3]


In [7]:
np.arange(0,12,3)

array([0, 3, 6, 9])

In [9]:
np.random.rand(2,2)

array([[0.67554706, 0.36707393],
       [0.62617497, 0.56268069]])

In [11]:
np.random.randint(2,20,5)

array([4, 8, 5, 9, 4])

In [16]:
np.random.randn(2,3,3)

array([[[ 0.53175159,  0.71488844, -1.23465358],
        [ 1.33555223,  0.78108633,  0.03825079],
        [-0.18841305, -0.02089709,  0.9698546 ]],

       [[-1.022244  , -1.62251982,  0.84376909],
        [ 1.90965557, -1.67999049, -0.64132845],
        [ 0.56276623,  1.50713001, -0.60914641]]])

In [8]:
arr.max()

3

In [9]:
my_array = np.array([[5,10,15],[20,43,54],[33,45,54]])
my_array

array([[ 5, 10, 15],
       [20, 43, 54],
       [33, 45, 54]])

In [14]:
my_array[1:,1:]

array([[43, 54],
       [45, 54]])

In [17]:
test_arr =np.arange(1,11)
test_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
bool_arr = test_arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
test_arr[test_arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.arange(60).reshape(6,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [28]:
arr_2d[3:5,4:6]

array([[34, 35],
       [44, 45]])